In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
#from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score
#from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix

In [47]:
# Assuming your data is in a CSV file named 'your_data.csv'
data = pd.read_csv('Robot_train_4s_1joint.csv')

data

,Label,X,Y,Z,X*Y,X*Z,Y*Z,X*Y+Z,X*Y*Z,X*Z+Y,...,slop(1/z),slop(1/x),slop(z/x),slop(z),slop(x)^2,slop(x/z)^2,slop(1/z)^2,slop(1/x)^2,slop(z/x)^2,slop(z)^2
0,-1,1044.181085,0.746138,0.387314,779.103186,404.425953,0.288990,779.490500,301.757571,405.172091,...,91.199270,0.62300,0.006832,0.010965,2.575925,21424.762920,8320.00000,0.388000,0.000047,0.000120
1,-1,1042.576116,0.746192,0.376349,777.961957,392.372479,0.280829,778.338306,292.785205,393.118671,...,153.092468,0.62300,0.004067,0.006532,2.579364,60453.348740,23400.00000,0.388000,0.000017,0.000043
2,-1,1040.970076,0.746208,0.369817,776.780198,384.968431,0.275960,777.150015,287.266523,385.714639,...,194.628260,0.62300,0.003198,0.005138,2.580556,97751.884530,37900.00000,0.388000,0.000010,0.000026
3,-1,1039.363665,0.746214,0.364679,775.587718,379.034102,0.272129,775.952397,282.840553,379.780316,...,212.856535,0.62200,0.002924,0.004698,2.580942,116937.066700,45300.00000,0.387000,0.000009,0.000022
4,-1,1037.757134,0.746215,0.359981,774.389940,373.572851,0.268623,774.749921,278.765665,374.319066,...,219.394471,0.62200,0.002837,0.004558,2.581067,124236.916600,48100.00000,0.387000,0.000008,0.000021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17950,17,-453.270635,0.749372,17.015462,-339.668322,-7712.609266,12.750911,-322.652860,-5779.613431,-7711.859894,...,-56.493983,0.62800,-0.011111,-0.017701,2.537821,8099.633923,3190.00000,0.394000,0.000123,0.000313
17951,17,-454.863689,0.749372,17.033163,-340.862112,-7747.767358,12.764175,-323.828949,-5805.959920,-7747.017986,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17952,17,-456.456743,0.749372,17.050863,-342.055902,-7782.981390,12.777439,-325.005039,-5832.348330,-7782.232018,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17953,17,-458.049797,0.749372,17.068563,-343.249692,-7818.251817,12.790703,-326.181129,-5858.779001,-7817.502445,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17954,17,-459.642851,0.749372,17.086263,-344.443483,-7853.578638,12.803967,-327.357219,-5885.251931,-7852.829266,...,0.058527,0.00218,-0.037173,17.086263,211271.550500,723.680459,0.00343,0.000005,0.001382,291.940383

In [48]:
print(data.keys())

Index(['Label', 'X', 'Y', 'Z', 'X*Y', 'X*Z', 'Y*Z', 'X*Y+Z', 'X*Y*Z', 'X*Z+Y',
       'Y*Z+X', 'X+Y', 'X+Z', 'Y+Z', 'X+Y+Z', 'X-Y', 'X-Z', 'Y-Z', 'X+Y-Z',
       'X-Y+Z', 'X-Y-Z', 'X/Y', 'X/Z', 'Y/Z', 'Y/X', 'Z/X', 'Z/Y', 'slop(x)',
       'slop(x/z)', 'slop(1/z)', 'slop(1/x)', 'slop(z/x)', 'slop(z)',
       'slop(x)^2', 'slop(x/z)^2', 'slop(1/z)^2', 'slop(1/x)^2', 'slop(z/x)^2',
       'slop(z)^2'],
      dtype='object')

In [49]:
y = data.pop('Label')
x = data
print(x.shape,y.shape)

(17955, 38) (17955,)

In [50]:
x

,X,Y,Z,X*Y,X*Z,Y*Z,X*Y+Z,X*Y*Z,X*Z+Y,Y*Z+X,...,slop(1/z),slop(1/x),slop(z/x),slop(z),slop(x)^2,slop(x/z)^2,slop(1/z)^2,slop(1/x)^2,slop(z/x)^2,slop(z)^2
0,1044.181085,0.746138,0.387314,779.103186,404.425953,0.288990,779.490500,301.757571,405.172091,1044.470075,...,91.199270,0.62300,0.006832,0.010965,2.575925,21424.762920,8320.00000,0.388000,0.000047,0.000120
1,1042.576116,0.746192,0.376349,777.961957,392.372479,0.280829,778.338306,292.785205,393.118671,1042.856945,...,153.092468,0.62300,0.004067,0.006532,2.579364,60453.348740,23400.00000,0.388000,0.000017,0.000043
2,1040.970076,0.746208,0.369817,776.780198,384.968431,0.275960,777.150015,287.266523,385.714639,1041.246036,...,194.628260,0.62300,0.003198,0.005138,2.580556,97751.884530,37900.00000,0.388000,0.000010,0.000026
3,1039.363665,0.746214,0.364679,775.587718,379.034102,0.272129,775.952397,282.840553,379.780316,1039.635794,...,212.856535,0.62200,0.002924,0.004698,2.580942,116937.066700,45300.00000,0.387000,0.000009,0.000022
4,1037.757134,0.746215,0.359981,774.389940,373.572851,0.268623,774.749921,278.765665,374.319066,1038.025757,...,219.394471,0.62200,0.002837,0.004558,2.581067,124236.916600,48100.00000,0.387000,0.000008,0.000021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17950,-453.270635,0.749372,17.015462,-339.668322,-7712.609266,12.750911,-322.652860,-5779.613431,-7711.859894,-440.519724,...,-56.493983,0.62800,-0.011111,-0.017701,2.537821,8099.633923,3190.00000,0.394000,0.000123,0.000313
17951,-454.863689,0.749372,17.033163,-340.862112,-7747.767358,12.764175,-323.828949,-5805.959920,-7747.017986,-442.099514,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17952,-456.456743,0.749372,17.050863,-342.055902,-7782.981390,12.777439,-325.005039,-5832.348330,-7782.232018,-443.679304,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17953,-458.049797,0.749372,17.068563,-343.249692,-7818.251817,12.790703,-326.181129,-5858.779001,-7817.502445,-445.259094,...,-56.497175,0.62800,-0.011111,-0.017700,2.537821,8100.549162,3190.00000,0.394000,0.000123,0.000313
17954,-459.642851,0.749372,17.086263,-344.443483,-7853.578638,12.803967,-327.357219,-5885.251931,-7852.829266,-446.838884,...,0.058527,0.00218,-0.037173,17.086263,211271.550500,723.680459,0.00343,0.000005,0.001382,291.940383

In [51]:
x =  data[['X', 'Z', 'slop(x)', 'slop(x/z)', 'slop(z)']]
X_train,X_test,y_train,y_test= train_test_split( x,y, test_size=0.2, random_state=42)

In [52]:
x

                 X          Z     slop(x)   slop(x/z)    slop(z)
0      1044.181085   0.387314   -1.604969  146.372002   0.010965
1      1042.576116   0.376349   -1.606040  245.872627   0.006532
2      1040.970076   0.369817   -1.606411  312.652978   0.005138
3      1039.363665   0.364679   -1.606531  341.960622   0.004698
4      1037.757134   0.359981   -1.606570  352.472576   0.004558
...            ...        ...         ...         ...        ...
17950  -453.270635  17.015462   -1.593054  -89.997966  -0.017701
17951  -454.863689  17.033163   -1.593054  -90.003051  -0.017700
17952  -456.456743  17.050863   -1.593054  -90.003051  -0.017700
17953  -458.049797  17.068563   -1.593054  -90.003051  -0.017700
17954  -459.642851  17.086263  459.642851  -26.901310  17.086263

[17955 rows x 5 columns]

In [59]:
rf_model_5 = RandomForestClassifier(random_state=42,max_depth=7,n_estimators=4)
rf_model_5.fit(X_train, y_train)

# 4. Model Evaluation
y_pred_5 = rf_model_5.predict(X_test)
accuracy_5 = accuracy_score(y_test,y_pred_5)
#print(f'Random Forest Accuracy: {accuracy_5}')
print("5 Features : 'X', 'Z', 'slop(x)', 'slop(x/z)', 'slop(z)'")
#cm=confusion_matrix(y_test,y_pred_7)
#plt.figure(figsize =(6,6))
#sns.heatmap(cm,annot=True,cmap='Blues',fmt='g',xticklabels=list(set(y_test)),yticklabels=list(set(y_test)))
#plt.xlabel('Predicted Label')
#plt.ylabel('True label')
#plt.show()
print(classification_report(y_test,y_pred_5))
print('Accuracy : ', accuracy_score(y_test, y_pred_5))

5 Features : 'X', 'Z', 'slop(x)', 'slop(x/z)', 'slop(z)'
              precision    recall  f1-score   support

          -1       1.00      0.97      0.99       177
           0       0.99      1.00      0.99       197
           1       0.99      0.99      0.99       185
           2       1.00      0.99      1.00       195
           3       0.71      0.99      0.83       181
           4       1.00      0.99      1.00       198
           5       1.00      1.00      1.00       180
           6       0.97      0.88      0.92       199
           7       1.00      1.00      1.00       209
           8       1.00      1.00      1.00       198
           9       0.99      0.97      0.98       184
          10       1.00      1.00      1.00       204
          11       1.00      0.99      1.00       191
          12       0.99      0.82      0.90       171
          13       1.00      0.99      0.99       176
          14       1.00      0.97      0.98       197
          15       0.99      0.97      0.98       182
          16       1.00      0.97      0.99       173
          17       1.00      0.99      1.00       194

    accuracy                           0.98      3591
   macro avg       0.98      0.97      0.98      3591
weighted avg       0.98      0.98      0.98      3591

Accuracy :  0.9757727652464494

In [66]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Load the CSV file into a DataFrame
two_joint_data = pd.read_csv('Robot_train_4s.csv')

# Filter the DataFrame to include only rows where the label is 0 or 1
filtered_data = two_joint_data[(two_joint_data['Label'] == "0&1")]

# Select features for prediction
features = ['X', 'Z', 'slop(x)', 'slop(x/z)', 'slop(z)']
X = filtered_data[features]
y = filtered_data['Label']


# Extract features of the first element
first_element = X.iloc[[10]]  # Reshape to 2D array-like


# Assuming the model has been fitted to the training data
# If not, fit the model to the training data here: model.fit(X, y)

# Make predictions for the new data
predictions = rf_model_5.predict(first_element)
print(y.iloc[[10]] )
print("Prediction for row:", predictions)

955    0&1
Name: Label, dtype: object
Prediction for row: [15]

In [80]:
label=two_joint_data['Label'].unique()

for label in label:
    print(label)

-1
0&1
0&2
0&3
0&4
0&5
0&6
0&7
0&8
0&9
0&10
0&11
0&12
0&13
0&14
0&15
0&16
0&17
1&2
1&3
1&4
1&5
1&6
1&7
1&8
1&9
1&10
1&11
1&12
1&13
1&14
1&15
1&16
1&17
2&3
2&4
2&5
2&6
2&7
2&8
2&9
2&10
2&11
2&12
2&13
2&14
2&15
2&16
2&17
3&4
3&5
3&6
3&7
3&8
3&9
3&10
3&11
3&12
3&13
3&14
3&15
3&16
3&17
4&5
4&6
4&7
4&8
4&9
4&10
4&11
4&12
4&13
4&14
4&15
4&16
4&17
5&6
5&7
5&8
5&9
5&10
5&11
5&12
5&13
5&14
5&15
5&16
5&17
6&7
6&8
6&9
6&10
6&11
6&12
6&13
6&14
6&15
6&16
6&17
7&8
7&9
7&10
7&11
7&12
7&13
7&14
7&15
7&16
7&17
8&9
8&10
8&11
8&12
8&13
8&14
8&15
8&16
8&17
9&10
9&11
9&12
9&13
9&14
9&15
9&16
9&17
10&11
10&12
10&13
10&14
10&15
10&16
10&17
11&12
11&13
11&14
11&15
11&16
11&17
12&13
12&14
12&15
12&16
12&17
13&14
13&15
13&16
13&17
14&15
14&16
14&17
15&16
15&17
16&17

In [87]:
two_joint_data[['Label_1', 'Label_2']] = two_joint_data['Label'].str.split('&', expand=True)
print("Unique values for Label_1:", two_joint_data['Label_1'].unique())
print("Unique values for Label_2:", two_joint_data['Label_2'].unique())

Unique values for Label_1: ['-1' '0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14'
 '15' '16']
Unique values for Label_2: [None '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17']

In [75]:
# Importing necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generating sample data
X, y = make_multilabel_classification(n_samples=100, n_features=10, n_classes=2, n_labels=1, random_state=42)

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Creating the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Creating MultiOutputClassifier
multi_target_rf = MultiOutputClassifier(rf_classifier, n_jobs=-1)

# Training the classifier
multi_target_rf.fit(X_train, y_train)

# Making predictions
y_pred = multi_target_rf.predict(X_test)
print(y_pred)

# Calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]]
Accuracy: 0.8

In [72]:
print(X)

[[ 3.  8.  5.  3.  1.  4.  2.  7.  4.  3.]
 [ 3.  1.  6.  4.  5.  3.  6.  2.  2.  4.]
 [ 4.  7. 14.  4.  6.  7.  5.  4.  3.  5.]
 [ 7.  0.  9.  6.  2.  4.  4.  8.  3. 10.]
 [ 3.  7.  5.  1.  5.  8.  5.  8.  3.  1.]
 [ 4. 13.  1.  0.  5.  5.  3. 13.  4.  2.]
 [ 3.  9.  7.  2.  2.  3.  3. 11.  7.  1.]
 [ 2. 16.  0.  1.  5.  5.  2. 11.  7.  5.]
 [ 1.  7.  5.  4.  5.  6.  4.  8.  6.  4.]
 [ 7.  9.  5.  3.  4.  6.  4.  4.  2.  5.]
 [ 7.  1.  6. 11.  2.  9.  0.  6.  3.  7.]
 [ 4.  3.  2.  5.  5.  7.  6.  4.  7.  5.]
 [ 8.  5.  5.  5.  6.  8.  2.  5.  3.  5.]
 [ 1.  9. 10.  5.  5.  4.  3.  8.  5.  1.]
 [ 2.  6.  4.  4.  5.  7.  3.  4.  8.  1.]
 [ 4. 15.  0.  0.  6.  4.  4. 10.  4.  2.]
 [ 3.  5.  6.  5.  6.  2.  6.  3.  1.  2.]
 [ 4.  8. 15.  2. 11.  6.  8.  1.  0.  1.]
 [ 3. 11.  0.  2.  1.  5.  2. 11. 15.  2.]
 [ 5.  4.  3.  3.  2.  1.  7.  4.  4.  4.]
 [ 5.  2.  3.  5.  6.  4.  3.  5.  7.  6.]
 [ 5. 10. 12.  2.  8.  7. 12.  4.  0.  1.]
 [ 5.  7.  5.  9.  1.  7.  5.  1.  2.  5.]
 [ 7.  6.  6.  5.  6.  8.  2.  9. 10.  2.]
 [ 2.  5.  0.  3.  1.  5.  2. 16.  8.  1.]
 [ 3.  2.  7. 11.  6.  8.  3.  4.  0.  2.]
 [ 2. 19.  0.  2.  6.  5.  6. 13.  4.  2.]
 [ 1.  6. 12.  2. 16.  7.  7.  4.  0.  1.]
 [ 1. 13.  4.  4.  6.  6.  4. 11.  3.  1.]
 [ 5.  1.  7. 13.  0.  6.  4.  4.  3.  3.]
 [ 2. 11.  6.  3.  4.  6.  4.  7.  3.  1.]
 [ 2. 14.  1.  2.  4.  4.  3. 14.  8.  0.]
 [ 6.  5.  2.  5. 10.  3.  4.  3.  4.  6.]
 [ 3. 17.  0.  1.  6.  9.  5.  8.  9.  5.]
 [ 5.  6.  7.  4.  8.  6.  8.  8.  6.  5.]
 [ 5.  9.  6.  4.  4.  4.  4.  9.  1.  2.]
 [ 3.  9.  5.  2.  5.  4.  2.  6.  5.  1.]
 [ 2. 13.  0.  4.  4.  4.  5. 13.  7.  4.]
 [ 2. 15.  1.  6.  8.  4.  5. 11.  8.  5.]
 [ 5.  5.  5.  4.  0.  2.  3.  7.  6.  1.]
 [ 3.  1.  8.  8.  3.  3.  3.  7. 10.  2.]
 [ 5.  4.  7.  6.  6.  8.  5.  6.  5.  1.]
 [10.  0.  6.  2.  5.  2.  4.  9.  5.  4.]
 [ 6.  9.  7.  5.  3.  3.  6.  3.  6.  6.]
 [ 3.  6.  2.  5.  5.  7.  0.  7.  2.  0.]
 [ 6.  5.  8.  5.  9.  5.  3.  1.  2.  7.]
 [ 5.  8.  0.  3.  2.  8.  5. 15.  8.  3.]
 [ 3.  8.  6.  2.  1.  4.  7.  5.  2.  0.]
 [ 5.  8.  2.  5.  5.  6.  5.  6.  6.  4.]
 [ 2. 11.  9.  4.  8. 10.  7.  5.  1.  1.]
 [ 5.  2.  3.  7.  7.  8.  5.  3.  5.  8.]
 [ 5.  7.  2.  7.  5.  6.  3.  9.  9.  8.]
 [ 3.  4.  6.  7.  6.  3.  3. 10.  3.  5.]
 [ 3.  8. 21.  1. 12.  6. 12.  2.  1.  1.]
 [ 6.  3.  5.  7.  7.  8.  4.  3.  8.  4.]
 [ 3.  7.  9.  4.  3.  7.  9. 10.  3.  2.]
 [ 4.  6.  4.  5.  3.  8.  7.  4.  7.  8.]
 [ 6.  0.  7.  7.  2.  7.  2.  9.  5.  6.]
 [ 5.  9.  4.  2.  3.  6.  3.  6.  3.  6.]
 [ 5.  1.  4.  6.  5.  3.  0.  5. 11.  3.]
 [ 1.  8.  0.  4.  4.  2.  6. 16.  7.  2.]
 [ 3. 11.  1.  1.  8.  6.  6. 10.  7.  2.]
 [ 4.  4.  4.  2.  4.  6.  4.  3.  3.  9.]
 [ 5.  4.  8.  5.  7. 10.  4.  9.  1.  3.]
 [ 2.  9.  5.  2.  6. 10.  8.  5.  5.  2.]
 [ 4.  4.  4.  6.  6.  1.  8. 11.  3.  5.]
 [ 0. 12.  0.  4.  6.  9.  7.  9.  9.  1.]
 [ 7.  4.  4.  6.  3.  7.  5.  6.  4.  5.]
 [ 5.  8. 15.  3.  6.  9.  6.  4.  0.  0.]
 [ 7.  6.  8.  8.  4.  4.  6. 10.  7.  9.]
 [ 3.  4.  3.  3.  8.  4.  6.  8.  5.  6.]
 [ 8.  0.  3.  0.  4. 10.  1.  4.  1.  4.]
 [ 6.  0.  7.  9.  1.  6.  2.  7.  4.  7.]
 [ 5.  7. 16.  1.  6.  8.  3.  3.  1.  1.]
 [ 5. 14.  9.  8.  4.  7.  3.  8.  4.  1.]
 [ 5.  8.  4.  7.  7.  1.  6.  4.  3.  9.]
 [ 5. 11.  2.  8.  4. 10.  2.  8. 10.  9.]
 [ 1. 10.  6.  3.  6.  3.  2.  6.  7.  2.]
 [ 0.  9.  9.  2.  5.  7.  3.  8.  7.  5.]
 [ 3. 17.  0.  3.  4.  5.  4.  8.  6.  1.]
 [ 3. 12.  0.  4.  4.  4.  3.  7.  7.  2.]
 [ 6.  1.  7.  9.  2.  4.  1.  1.  7.  6.]
 [ 4.  9.  7.  4.  2.  5.  7.  6.  7.  3.]
 [ 6.  9. 11.  8.  2.  4.  5.  4.  2.  2.]
 [ 3.  8.  5.  6.  3.  3.  4.  3. 10.  5.]
 [ 4.  8. 13.  1.  5.  5.  4.  3.  0.  0.]
 [ 1.  9. 13.  2.  8.  9.  7.  3.  0.  1.]
 [ 5.  5.  8.  4.  6.  3.  3.  2.  8.  2.]
 [ 8.  8.  0.  4.  2.  7.  6.  4.  4.  4.]
 [ 7.  4.  7.  4.  1.  9.  6.  8.  4.  6.]
 [ 8.  5.  3.  4.  7.  7.  5.  1.  2.  4.]
 [ 0.  9.  0.  0.  4.  6. 11. 15.  8.  1.]
 [ 3. 13.  1.  5.  1.  7.  5. 14.  7.  1.]
 [ 5.  1.  5.  9.  4.  7.  0.  6.  7.  3.]
 [ 4.  6.  5.  2.  3.  4.  4.  5.  5.  7.]
 [ 2.  3.  2.  3.  5.  9.  4.  6.  2.  5.]
 [ 4.  8.  3.  7.  3.  1.  4.  6.  5.  9.]
 [ 2.  8.  8.  3. 10.  5.  5.  3.  0.  1.]
 [ 2.  2.  4.  3.  7.  6.  2.  4.  4.  7.]
 [ 2.  6. 12.  5.  4.  9.  4.  1.  1.  0.]]

In [73]:
print(y)

[[1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [0 1 1]
 [0 1 0]
 [0 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 0]
 [0 1 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [1 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]]